# Generated by Django 3.2.6 on 2021-08-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookreporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '책', 'verbose_name_plural': '책 목록'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': '장르', 'verbose_name_plural': '장르 목록'},
        ),
        migrations.AddField(
            model_name='quote',
            name='page',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20, verbose_name='작가'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.URLField(verbose_name='구매 링크'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreporter.genre', verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='표지'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=20, verbose_name='출판사'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=30, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='phrase',
            field=models.TextField(verbose_name='인용구'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(verbose_name='리뷰'),
        ),
    ]
