# Generated by Django 3.2.6 on 2021-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreporter', '0002_auto_20210812_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='page',
            field=models.IntegerField(),
        ),
    ]
